# Generated by Django 6.0.3 on 2026-05-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('reviewed', 'İncelendi'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri Çekildi')], default='pending', max_length=20),
        ),
    ]
