# Generated by Django 6.0.3 on 2026-04-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_application_deadline_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Tam zamanlı', 'Tam Zamanlı'), ('Yarı zamanlı', 'Yarı Zamanlı'), ('Staj', 'Staj'), ('Uzaktan', 'Uzaktan'), ('Hibrit', 'Hibrit'), ('Ofis', 'Ofis')], default='full_time', max_length=50),
        ),
    ]
