# Generated by Django 6.0.3 on 2026-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_sector_alter_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
