# Generated by Django 6.0.3 on 2026-05-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_city_job_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='optional_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
