# Generated by Django 6.0.3 on 2026-05-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_optional_skills_alter_job_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Tam Zamanlı', 'Tam Zamanlı'), ('Yarı Zamanlı', 'Yarı Zamanlı'), ('Staj', 'Staj'), ('Uzaktan', 'Uzaktan'), ('Hibrit', 'Hibrit'), ('Ofis', 'Ofis')], default='full_time', max_length=50),
        ),
    ]
